### ISSUE TITLE
Get rid of "CFBundleIdentifier" error

### ISSUE THREAD

**Issue by grabbou** [react-native-community/react-native-cli#107]
This is super old issue that happens when you run "run-ios" (usually for the first time on a newly inited project). It's one of the pinned issues in React Native and one of the most popular errors people are struggling with.

If this is a "wont fix", we should consider changing the logic of the command itself to avoid this mistake. 

I am opening this issue as a memo for the future.

Related: https://github.com/facebook/react-native/issues/21303

Stack trace:
```
Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/RNTesterPods.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

    at checkExecSyncError (child_process.js:611:11)
    at Object.execFileSync (child_process.js:629:13)
    at Promise.then (/Users/grabbou/Repositories/react-native/node_modules/@react-native-community/cli/build/runIOS/runIOS.js:183:36)
```

**Comment by Kielan** [comment]
I agree! I have my own internal documentation on all of the possibilities that can cause the :CFBundleIdentifier error but it needs to be clear for everyone.

**Comment by mschipperheyn** [comment]
Obviously, compilation failed. But a little helpful context, goes a long way.
`An application bundle was not found at the provided path.` WHICH path? Just so we can perhaps easily debug a path problem.
