### ISSUE TITLE
Don't copy font files into "assets" android folder in "react-native link"

### ISSUE THREAD

**Issue by punksta** [react-native-community/react-native-cli#111]
`react-native link` is copping all fonts into assets folder for android. 
For ios it is registering font files in ios project file without making files copies.

### problem
I don't want to store copies of all fonts in android assets folder.

### Suggestion 
There are few ways of solving this:
1) We can make gradle task in https://github.com/facebook/react-native/blob/master/react.gradle which will copy font files in "generated/assets" in build time. So fonts will be synced automatically same as images.
I don't know is something similar possible for ios (registering fonts files in build time, without changing source code files)
2) to make behavior similar to ios `link` command could just create text file file with font paths to track them instead of making copies. We can add this file to git. And then gradle task adds only fonts from this file, not all of them.

originally posted here https://github.com/react-native-community/discussions-and-proposals/issues/89

**Comment by thymikee** [comment]
We have quite a bunch of issues regarding improvements in link command, can you check if any of those relate to your request? Would be nice to consolidate some stuff if possible, but I think this one makes sense on its own.

cc @ferrannp @grabbou

**Comment by grabbou** [comment]
I am sorry @punksta to let you know, but this is unfortunately not a CLI issue. I will comment on the original issue with the details.

Thanks for filling this in - I didn't now that another way of doing that was possible.
