### ISSUE TITLE
Convert requires to imports

### ISSUE THREAD

**Issue by thymikee** [react-native-community/react-native-cli#114]
Thanks to using `import`s instead of `require`s we're able to apply import transform to inline requires for faster startups :) 

Basically like this:

```diff
-const path = require('path');
+import path from 'path';
```

**Comment by Trancever** [comment]
@thymikee I can try to do it. Assign me if possible.

**Comment by sidferreira** [comment]
@Trancever I worked this morning on this but I haven't seen that you wanted to help. 

If you haven't started yet, you can take a look at https://github.com/sidferreira/react-native-cli/tree/refactor/replacesRequiresByImports and help me to check if there's anything missing...

**Comment by Trancever** [comment]
@sidferreira Hi, I finished refactoring the codebase but I am currently struggling with making test passing again. I'll dm you tomorrow so we can collaborate on this.

**Comment by Trancever** [comment]
@thymikee I believe this can be closed. We can open another issue for replacing module.exports with ES module exports.
