### ISSUE TITLE
ECONNRESE: cli process crashes sometimes. 

### ISSUE THREAD

**Issue by EltonZhong** [react-native-community/react-native-cli#131]
## Environment

  React Native Environment Info:
    System:
      OS: Linux 3.10 CentOS Linux 7 (Core)
      CPU: (4) x64 AMD Opteron(tm) Processor 6348
      Memory: 1.88 GB / 7.64 GB
      Shell: 4.2.46 - /bin/bash
    Binaries:
      Node: 11.6.0 - ~/.nvm/versions/node/v11.6.0/bin/node
      npm: 6.5.0-next.0 - ~/.nvm/versions/node/v11.6.0/bin/npm
    npmPackages:
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz => 0.57.1

## Description
Process crashes often with information below:
![image](https://user-images.githubusercontent.com/20570738/51816345-1ffb1980-2301-11e9-8444-f7db7801c8cf.png)

And the process is:
`
root     27491  0.3  1.0 938304 84540 ?        Sl   10:43   0:29 /root/.nvm/versions/node/v11.6.0/bin/node /root/pixies/pixies-app/node_modules/react-native/local-cli/cli.js start --port 19001 --customLogReporterPath /root/pixies/pixies-app/node_modules/expo/tools/LogReporter.js --assetExts ttf --reset-cache
`

See [Expo ticket](https://github.com/expo/expo/issues/3227) for full details.

## Reproducible Demo

expo start a simple project on linux server, and open exp:xxx:19000 on many android/ios devices.

**Comment by EltonZhong** [comment]
![image](https://user-images.githubusercontent.com/20570738/51819233-a2d5a180-230c-11e9-9951-23f6f811e67d.png)
Would logic above help?

**Comment by thymikee** [comment]
Are you able to reproduce this on a clean project without Expo?

**Comment by EltonZhong** [comment]
> Are you able to reproduce this on a clean project without Expo?

Well, I can't find a consistent way to reproduce it. It's not happening regularly, but it does crash sometimes and influent a lot.

**Comment by thymikee** [comment]
Closing, as reading through the comments in the linked issue it seems like an Expo problem.
