### ISSUE TITLE
Exclude a package from react-native link

### ISSUE THREAD

**Issue by ferrannp** [react-native-community/react-native-cli#17]
See: https://stackoverflow.com/questions/49851602/how-do-i-exclude-a-package-from-react-native-link

I think this will be useful (and maybe even necessary if some libraries break).

**Comment by n1ru4l** [comment]
Yes IMHO libraries should defined whether they can be `react-native link`'ed or not.

**Comment by grabbou** [comment]
Closing in favour of #48
