### ISSUE TITLE
Normalize project name 

### ISSUE THREAD

**Issue by grabbou** [react-native-community/react-native-cli#203]
We need to escape `@` from the package name. Otherwise, it's causing errors with latest Gradle: https://github.com/react-native-community/react-native-netinfo/issues/27

We most likely need to update https://github.com/react-native-community/react-native-cli/blob/master/packages/cli/src/link/android/patches/normalizeProjectName.js

**Comment by FLGMwt** [comment]
Looks like:

- remove '@'s
- replace '/'s with '-'

matt-oakes had to do both w/ netinfo

**Comment by grabbou** [comment]
Turned out to be not an issue according to @matt-oakes. Going to close this one (tho we could get rid of `@` because it looks a bit ugly - if anyone cares)

**Comment by FLGMwt** [comment]
SGTM, I guess I'll just find another reason to play around with my clone of -cli then ; D

**Comment by matt-oakes** [comment]
Just to confirm, it was only the `/` which was in the disallowed list, `@` is actually fine. This is from the Gradle 5 error message:

```
project name '@react-native-community/netinfo' must not contain any of the following characters: [/, , :, <, >, ", ?, *, |].
```
