### ISSUE TITLE
Decouple CLI from Metro

### ISSUE THREAD

**Issue by grabbou** [react-native-community/react-native-cli#21]
In order to support different bundlers in the future (and also to clean up the codebase a bit), we should make a separate package for the `server` command. That would allow us prepare for decoupling in the future, but also to further decouple CLI from Metro where it doesn't need to use it.

**Comment by empyrical** [comment]
Maybe a new plugin format could be made, like: `rnpm-bundler-metro`, `rnpm-bundler-haul`, `rnpm-bundler-parcel`, etc? and `app.json` could have the preferred bundler specified

**Comment by grabbou** [comment]
Yeah. That's the way to go. We need to now extract "Metro" into a separate plugin to start with. Going to open an additional issue to track that.
