### ISSUE TITLE
Bump metro dependencies

### ISSUE THREAD

**Issue by belemaire** [react-native-community/react-native-cli#210]
Would it be possible to bump the version of metro dependencies in next release ?

We're currently evaluating upgrade to RN 59 (using RC 3 as of now) for one of our application, and we faced a new error during bundling. After taking a closer look we realized that we were running into a metro bug, related to assets path resolution, that was fixed in Metro 0.52.0 (https://github.com/facebook/metro/commit/ce6824ced730d4aa6c4b63c007ed915e1180c258).
Manually updated cli metro dependencies locally to give it a try, and bundling issue was gone.

Thanks.

**Comment by thymikee** [comment]
Yup we shuold bump it, even though it's possibly breaking change (0.59 is the first public version this CLI is used in). Want to send a PR?
