### ISSUE TITLE
Printing help for commands without description

### ISSUE THREAD

**Issue by grabbou** [react-native-community/react-native-cli#214]
Follow up to: https://github.com/facebook/react-native/pull/22045 - investigate the patch.

**Comment by thymikee** [comment]
This is already fixed:

https://github.com/react-native-community/react-native-cli/blob/ccc179737b0aea3d0979bd2777f9ea4b50ad83a3/packages/cli/src/cliEntry.js#L55

**Comment by grabbou** [comment]
Yes. Maybe I wasn't clear but following up my comment [here](https://github.com/facebook/react-native/pull/22045#issuecomment-471562100), the fix on line `55` (to conditionally check for description) is hacky. 

We are setting `noHelp` in a different place to avoid calling this function w/o description set. In other words, this function should be called only when description is defined. If that's not the case, our assumptions somewhere in the code are invalid and we should track that down.

**Comment by thymikee** [comment]
I foolishly assumed this was merged. We need to take a look
