### ISSUE TITLE
Debugger is not opening anymore with 1.4.0

### ISSUE THREAD

**Issue by jacargentina** [react-native-community/react-native-cli#225]
## Description

I 'm cross posting here, as it seems a bug originated on the CLI and not RN 0.59.0

https://github.com/facebook/react-native/issues/23873

## Reproducible Demo

* I've upgraded my project to RN 0.59.0 + "@react-native-community/cli": "^1.4.0"
* Trying to debug my app shows the provided screenshot on the issue i've linked
* I've downgraded to "@react-native-community/cli": "^1.3.2", and debugging works just fine again.

**Comment by thymikee** [comment]
I can confirm that's a bug, please close the corresponding issue in RN repo

**Comment by thymikee** [comment]
Fixed in 1.4.1. Thanks for reporting this quickly!

**Comment by SaraChicaD** [comment]
How do you get this to kick in? I can only get projects _created_ with the right version to catch the debugger correctly. I've installed/uninstalled `react-native-cli` removed `node_modules`, restarted the computer, how do you get `1.4.1` to kick in correctly?

**Comment by thymikee** [comment]
Remove and add react-native with the same version. react-native-cli is a global cli (a proxy to the real one, it hasn't been touched for 2 yrs). We know it's confusing and working towards fixing it
