### ISSUE TITLE
development server returned response error code 500

### ISSUE THREAD

**Issue by suyashinpilani** [react-native-community/react-native-cli#247]

**Comment by suyashinpilani** [comment]
development server returned response error code 500

![image](https://user-images.githubusercontent.com/44916943/54568471-4e41cf00-49fd-11e9-9a90-c623ceddf227.png)


I have tried literally everything what people are calling as a solution and worked for them but it is not working for me. 
clearing npm cache, reinstalling npm
changing versions of react native etc
nothing works for me.
What should i try?

**Comment by Esemesek** [comment]
https://stackoverflow.com/questions/22475849/node-js-what-is-enospc-error-and-how-to-solve

**Comment by suyashinpilani** [comment]
Thanks, it worked for me with an addition of 
adb reverse tcp:8081 tcp:8081
