### ISSUE TITLE
ASCII art for init command

### ISSUE THREAD

**Issue by patrickkempff** [react-native-community/react-native-cli#266]
Lets make the init command looking really awesome with some nice ascii art! I have spend some time trying to give the init command a cleaner look and posted a screenshot and video of the result here https://github.com/react-native-community/react-native-cli/issues/91#issuecomment-475914736. 

Based on @thymikee comment I have tried some different variations and sizes. I would love to discuss those.

There are different terminals, platforms and configurations out there. We should make sure that the ASCII image is recognizable a cross different platforms. We could learn from the yeoman implementation: https://github.com/yeoman/yosay

**Original:**

https://sendvid.com/embed/a9lrtvjj

<img width="973" alt="54873024-0f7d9180-4dce-11e9-8eb0-ffe3cab33dc1" src="https://user-images.githubusercontent.com/310766/54879968-fb727800-4e3f-11e9-9d46-6062ecbf40e4.png">

Variant 2
--------------
![variant 2](https://user-images.githubusercontent.com/310766/54883068-7a2bdd00-4e61-11e9-9c6c-2ddfac696a5b.png)

Variant 3
--------------
![variant 3](https://user-images.githubusercontent.com/310766/54883071-8dd74380-4e61-11e9-8c7e-c5dad7d02c21.png)

Variant 4
--------------
![variant 5](https://user-images.githubusercontent.com/310766/54880184-73da3880-4e42-11e9-9501-56d6e4442392.png)

Variant 5
--------------
![variant 5](https://user-images.githubusercontent.com/310766/54883093-f1fa0780-4e61-11e9-882c-ca92edafde67.png)

Variant 6
--------------
![variant 6](https://user-images.githubusercontent.com/310766/54883099-076f3180-4e62-11e9-8833-b35962c68fd9.png)

Variant 7
--------------
![variant 7](https://user-images.githubusercontent.com/310766/54883113-34bbdf80-4e62-11e9-80ae-ced1720163c7.png)

Variant 8
--------------
![variant 8](https://user-images.githubusercontent.com/310766/54883369-8fa30600-4e65-11e9-93ee-721673eefa30.png)

Variant 9
--------------
![variant-9](https://user-images.githubusercontent.com/310766/54935441-9b073780-4f20-11e9-991c-ac5b49a771f5.png)

Although I tried to include multiple sizes, small that variant will render the logo unrecognizable. Variant 8 is the smallest I could get, but I can spend some time trying to create a smaller version.

What do you think? Please be critical!

**Comment by thymikee** [comment]
I think I like the Variant 5 the most :) Awesome work!

**Comment by MarcelBreasWAY** [comment]
Variant 6

**Comment by grabbou** [comment]
Why don't we ship both and make a secret flag? Just kidding. 

This is amazing work, I am so excited to see this finally implemented, great job! I am also voting for 5/6.

**Comment by weareyou-laurens** [comment]
My vote goes to variant 3.

**Comment by cpojer** [comment]
This is super cool! I would suggest 4, 7 or 8 because they take up less vertical space.

**Comment by basfluijt** [comment]
Variant 2

**Comment by paullaros** [comment]
5

**Comment by patrickkempff** [comment]
Awesome, thanks for the responses! Added variant 9, basically the same 5 but more smooth.

**Comment by Esemesek** [comment]
This is amazing. Number 5 the best C:

**Comment by disenio** [comment]
Great work! 5 get's my vote!

**Comment by dirkpostma** [comment]
Very cool!! #6

Does it animate?

**Comment by patrickkempff** [comment]
@dirkpostma I tried some simple animations but could not do it in a reliable way, it has a lot of limitations. Terminal support is a problem as well.  Did also some tests animating colors with chalk-animation see https://sendvid.com/ezmgdcqt
