### ISSUE TITLE
React-Native linking issue

### ISSUE THREAD

**Issue by AlexMachin1997** [react-native-community/react-native-cli#284]
## Environment

```
  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
      Memory: 2.12 GB / 7.85 GB
    Binaries:
      Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.3.0.0 AI-182.5107.16.33.5314842

```
## Description
React-Native cli is currently linking native modules such as react-native-gesture-handler incorrectly. Within `./android/settings` it's pointing to the node_modules incorrectly, backslashes are used instead of forward slashes. 

**What I exepct:**
`project(':react-native-gesture-handler').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-gesture-handler/android')`

**What the actual behaviour is:**
`project(':react-native-gesture-handler').projectDir = new File(rootProject.projectDir, '..\node_modules\react-native-gesture-handler\android')`

## Reproducible Demo
https://github.com/AlexMachin1997/React-Native-Linking-Issue

**Comment by thymikee** [comment]
We fixed this in RN 0.59. Please use it instead, as 0.58 is not receiving updates and this repository has has the cli that's only used in 0.59+
