### ISSUE TITLE
Naming strategy

### ISSUE THREAD

**Issue by grabbou** [react-native-community/react-native-cli#29]
Opening this issue to discuss the naming strategy for packages included in this repository in the npm registry.

Right now, there's this concept of a global CLI. It's meant to be installed only once and rarely updated. It's a single file that does two things:
- it installs `react-native` from npm registry and uses `local-cli` bundled with it to init a new project
- it proxies all calls to `node_modules/react-native/local-cli/cli.js` when run in context of a React Native project

Ultimately, I would like to deprecate the second use-case now that we can just do `yarn react-native` and execute the `node_modules` CLI automatically.

Because the `react-native-cli` name is already taken by the global CLI, it makes it tricky to find a good name for the `local-cli`, that is, the real CLI where all the tools and commands are located.

`react-native-local-cli` is not much descriptive as pointed out by @cpojer and closes the door to modify the structure in the future. If we ever deprecate `react-native-cli` (global one) in favour or more user-friendly tools, the `react-native-local-cli` will make no sense to people that didn't remember it living in the React Native repository or having the global package.

Other ideas are `react-native-scripts`. 

What do you think?

**Comment by grabbou** [comment]
^ `react-native-scripts` is already taken by `create-react-native-app`. That said, the only alternative that comes to my mind is `react-native-tools`.

It's [already taken](https://www.npmjs.com/package/react-native-tools), but I think we can do something about it.

**Comment by cpojer** [comment]
Yep, just adding here that as we are thinking of taking the cli out of the RN repo, it's a good opportunity to rethink the naming. `react-native-cli` absolutely makes sense as it is the user-visible entry point but the `local` in `react-native-local-cli` is not adding any value and I believe it's actually confusing when people have to deal with it.

**Comment by thymikee** [comment]
How about using scoped packages and have `@react-native/cli`, is that possible?

**Comment by cpojer** [comment]
I think @thymikee’s suggestion makes a ton of sense.

**Comment by grabbou** [comment]
Right. I believe we already had a discussion regarding scoping slimenned modules under `react-native` namespace and came to a conclusion not to do so. 

CC: @kelset do you remember this?

Either way, this means that:
a) we need to change `react-native-cli` to `@react-native/cli` which is a breaking change for all the people that have it already installed globally and something we wanted to avoid
b) we still don't have a good name for the `local-cli`

**Comment by cpojer** [comment]
I would propose to keep `react-native-cli` as the global module, and rename the local cli to `@react-native/cli`. That way you have a global entry-point, but a scoped module that does all the work.

**Comment by grabbou** [comment]
Going to go with `@react-native/cli` for the initial release.
