### ISSUE TITLE
Rename repository to just `react-native-community/cli`

### ISSUE THREAD

**Issue by thymikee** [react-native-community/react-native-cli#298]
## Ask your Question

`react-native-community/react-native-cli` -> `react-native-community/cli` 

There's unnecessary duplication of `react-native` in our repository name. I think we should be good with just `cli` instead `react-native-cli`.

Pros:
- it would correspond directly with our main package name on npm `@react-native-community/cli`
- renaming GitHub repos is fairly straight-forward and supports redirecting

Cons:
- changing links to issue tracker (old ones will still be redirected)

cc @grabbou @cpojer

**Comment by cpojer** [comment]
I'm fine with this.

**Comment by grabbou** [comment]
Done.
