### ISSUE TITLE
react-native link react-native-webview fail

### ISSUE THREAD

**Issue by codeprolin** [react-native-community/react-native-cli#301]
## Ask your Question

run -------- react-native link react-native-webview

error Something went wrong while linking. Error: Expected "/ Begin ", "/ End ", """, or [A-Za-z0-9_.] but "<" found.
Please file an issue here: https://github.com/react-native-community/react-native-cli/issues**

So, how to resolve?

**Comment by thymikee** [comment]
Please use issue template properly and provide repro. Otherwise it's not actionable in our side
