### ISSUE TITLE
--appFolder on Android not really working as expected

### ISSUE THREAD

**Issue by ferrannp** [react-native-community/react-native-cli#32]
Let's say you have more than 1 app in your android directory. When you do:

```bash
react-native run-android --appFolder someAppFolder
```

It is installing all apps. This is because under the hood the cli is running `./gradlew installDebug`. (or whatever variant). Instead it should be:

```bash
./gradlew :someAppFolder:installDebug
```

**Comment by grabbou** [comment]
Is the use-case having many apps under `android` folder or simply having a different than `app` name?

What are the multiple apps for? Are all of them React Native ones? Trying to understand how e.g. `link` command should behave in such case.

**Comment by grabbou** [comment]
Shall we detect when there are multiple apps and print a warning that multiple apps were detected and we selected the first one. Pass `--appFolder` flag to choose an appropriate one.
