### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by grabbou** [react-native-community/react-native-cli#35]
There's a lot on the plate to be done in the upcoming months, I am going to write here a roadmap really soon for you to check and give some suggestions.

Right now, I want to focus on high-priority tasks (bug-fixing, improving "obvious" issues) while keeping work on the v2 in the meantime).

**Comment by grabbou** [comment]
We are wrapping up our work on high-priority issues. We are having an internal meeting next week to discuss the future roadmap and areas where we have to improve.

If you are reading it and want to be part of such meeting, please let me know.

**Comment by pvinis** [comment]
Yes, please. How would that work? Thanks.

**Comment by grabbou** [comment]
@pvinis we just had the meeting few days ago - I'll let you know when the next comes up upfront!
