### ISSUE TITLE
Use the template from React Native

### ISSUE THREAD

**Issue by cpojer** [react-native-community/react-native-cli#39]
The template can now be found in the root of react-native here: https://github.com/facebook/react-native/tree/master/template

Using the template from RN will allow us to keep the template in sync with RN, and it will allow the CLI to work with different versions of RN. If we do not use the template from the RN repo, the CLI repo will need to maintain the template for each version of RN it supports.

**Comment by grabbou** [comment]
Thanks! I'll work on that as soon as my other PR gets merged. We need to implement this before cutting next RC.

**Comment by Esemesek** [comment]
I was investigating this issue. We can use `svn` to get the files without cloning the whole `react-native` repository. Sadly, `git` doesn't support this use case.
```sh
svn checkout https://github.com/facebook/react-native/trunk/template
```

**Comment by grabbou** [comment]
Not sure we need it. If you look at the init script - it installs React
Native to node_modules and they are already present at the time of the
command running. We can just access them from that folder.

**Comment by Esemesek** [comment]
Right. Forgot we have it already there :P

**Comment by gengjiawen** [comment]
Is there anyway I can init template from the `facebook/react-native` repo now ?

**Comment by grabbou** [comment]
Not yet, in a day or two, when we release this version, you will be able to just use the CLI to do it.
