### ISSUE TITLE
Run-android does not support launching Activity with different applicationId from package name defined in productFlavor

### ISSUE THREAD

**Issue by bartolkaruza** [react-native-community/react-native-cli#40]
Migrated from React Native: 
https://github.com/facebook/react-native/issues/22022

**Comment by grabbou** [comment]
Thanks for importing this issue. Have you tried using `--appId` flag available for `react-native run-android`? 

If yes, and it doesn't provide expected results, then it's something we should definitely fix.

**Comment by grabbou** [comment]
@bartolkaruza, were you able to confirm if my suggestion fixes the issue?

**Comment by bartolkaruza** [comment]
Thanks for the reminder, just checked; works as documented and expected. Thanks a lot!

```
...
    defaultConfig {
        applicationId "com.flavorrunandroid"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
...
    flavorDimensions "colors"
    productFlavors {
        blue {
            applicationIdSuffix ".blue"
        }
    }
...
```

```react-native run-android --variant=blueDebug --appId=com.flavorrunandroid.blue```

**Comment by Ragzzy-R** [comment]
I am having this same issue for a different scenario.  We wanted to rename the root package as we had some issues with the playstore and now my `react-native run-android` don't work. 

I renamed the files properly on android studio side and it builds without any error.
I changed the  `external.linked.project.id="com.yourstory.mobile"`  attribute of `<Module>` in the .iml file.
changed rootproject name in settings.gradle and still i couldnt run it.

So I used the `--appId` flag and still although the appId was detected correctly, it was searching for the MainActivity on the old folder which doesnt exist anymore

running `react-native run-android --main-activity com.yourstory.mobile.MainActivity --appId com.yourstory.mobile`

gave me 
```

Starting the app (F:\Android_SDK/platform-tools/adb shell am start -n com.yourstory.mobile/com.yourstory.MainActivity..
Starting: Intent { cmp=com.yourstory.mobile/com.yourstory.MainActivity }
Error type 3
Error: Activity class {com.yourstory.mobile/com.yourstory.MainActivity} does not exist.
```
 

running `react-native run-android --main-activity InvalidActivity --appId com.yourstory.mobile`

also gave me 
```

Starting the app (F:\Android_SDK/platform-tools/adb shell am start -n com.yourstory.mobile/com.yourstory.MainActivity...
Starting: Intent { cmp=com.yourstory.mobile/com.yourstory.MainActivity }
Error type 3
Error: Activity class {com.yourstory.mobile/com.yourstory.MainActivity} does not exist.

```


it looks like its not reading the --main-activity flag. Or maybe I'm doing it wrong. Pls someone guide me.

PS: the project was building the `--appId` flag was working fine
