### ISSUE TITLE
Move "core" to a separate package, such as "cli-tools"

### ISSUE THREAD

**Issue by grabbou** [react-native-community/react-native-cli#49]
The `local-cli/core` is not really a core, it's just a set of useful "tools" that can be used to locate iOS project somewhere etc. 

In order to make it easy for other plugins and packages to use this, we should definitely make it a separate package with public interface. 

Right now, some developers are requiring them directly from "build" or "src" folder, which is dangerous.

**Comment by gengjiawen** [comment]
Some features I love to have:
* Like add util wait for emulator online. Make it easier for android to do instrumentation test.

**Comment by grabbou** [comment]
CC: @fson - this is definitely area for us to discuss
