### ISSUE TITLE
New Typescript projects created with the CLI do not build/run correctly

### ISSUE THREAD

**Issue by bartolkaruza** [react-native-community/react-native-cli#65]
Migrated from RN core: https://github.com/facebook/react-native/issues/22914

This issue covers points 2 and 3 from the React Native issue posted above.

> The project does not run. After building the project and attempting to run the project on a connected device and that fails because it's looking for the APK file in the wrong place, e.g. react-native run-android --deviceId <my device id> results in the following:
adb: failed to stat app/build/outputs/apk/app-debug.apk: No such file or directory
Command failed: /usr/local/share/android-sdk/platform-tools/adb -s 99523a0828712a92 install app/build/outputs/apk/app-debug.apk
Could not install the app on the device, read the error above for details.

> This is because the APK builds to apk/debug/app-debug.apk, not apk/app-debug.apk!!!

> I even tried explicitly adding the --variant debug flag and it still insists on looking for the APK in the parent folder (instead of in the "debug" child folder where the APK was built to).

**Comment by grabbou** [comment]
So this issue can be divided into two, separate parts: First, the OP has problems getting Typescript up & running (which is something to report to the maintainers of the Typescript template) and building the app on the simulator - which is something we should probably look at.

**Comment by grabbou** [comment]
I wasn't able to reproduce this issue. 

Closing as per this comment: https://github.com/facebook/react-native/issues/22914#issuecomment-452400079
