### ISSUE TITLE
assetExts passed to `react-native start` as a command line argument is ignored

### ISSUE THREAD

**Issue by fson** [react-native-community/react-native-cli#68]
I found this bug in React Native v0.57 and even though the Metro config handling in `react-native start` has changed a bit since then, it looks like this bug exists in `react-native-local-cli` as well.

It seems that we need to handle `assetExts` here, the same way `sourceExts` are handled: https://github.com/react-native-community/react-native-cli/blob/6de63fed2c931ba15296b3d51d85332030d741fd/packages/local-cli/server/runServer.js#L55

**Comment by grabbou** [comment]
Going to be fixed in #56
