### ISSUE TITLE
Improve start-up time

### ISSUE THREAD

**Issue by grabbou** [react-native-community/react-native-cli#7]
We need Babel because there are Flow types inside. 

We should consider the following:
- convert the whole project to Typescript
- pre-compile the CLI before publishing to `npm` to speed up the start-up time (which is extremely slow right now)

I guess we can start with the latter and consider doing the former at some point. I am also a big supporter of ReasonML and would love seeing parts of the CLI being written in it.

CC: @esemesek

**Comment by thymikee** [comment]
Also use [inline-requires](https://github.com/zertosh/babel-plugin-transform-inline-imports-commonjs) once we have the compilation, should speedup the init load significantly
