### ISSUE TITLE
Missing issue and PR templates

### ISSUE THREAD

**Issue by Esemesek** [react-native-community/react-native-cli#70]
We should add issue and PR templates to meet community standards. It should be something simmilar to https://github.com/facebook/react-native/tree/master/.github .

**Comment by grabbou** [comment]
Good idea.

@Titozzz - do you have something already set up in WebView that we could treat as a "standard"? If not, let's pick something and see if we can use it together.

**Comment by Titozzz** [comment]
We reeeeeally need one and we don't have one yet so I'm very happy to discuss that

**Comment by grabbou** [comment]
Some inspiration from another community package: https://github.com/react-native-community/react-native-camera/tree/master/.github/ISSUE_TEMPLATE
