### ISSUE TITLE
Project from react-native init no longer includes __tests__ directory

### ISSUE THREAD

**Issue by ashfurrow** [react-native-community/react-native-cli#88]
Originally opened here: https://github.com/facebook/react-native/issues/19761

The project generated by running `react-native init` no longer includes a `__tests__` directory. At some point, it did but I can't find where in any changelogs that it was removed. I most recently tested this with `react-native-cli` version 2.0.1; you can read the issue linked to above for more context. 

The `init` command appears to pull in the template from [this directory of the react-native repo](https://github.com/facebook/react-native/tree/aba4ec0c0984caf3bec75a803080bd95722b35db/local-cli/templates/HelloWorld), which includes a `__tests__` directory, but I took a look around and I'm not sure what the problem is. I'm happy to help provide more details or dive into debugging this with some guidance. Thanks!

**Comment by Esemesek** [comment]
This is no longer a case on `master` branch. The newly inited project includes `__tests__` directory.

**Comment by ashfurrow** [comment]
Cool, thanks! Looking forward to it getting released.
